language: csharp
mono: none
dotnet: 3.1
before_install:
- sudo apt-get -y install pam libpam0g-dev
install:
- dotnet restore
script:
- dotnet build
- ./test/setup_test_account.sh
- dotnet test test/Npam.Tests/Npam.Tests.csproj

